# Generated by Django 5.2.16 on 2026-07-23 17:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streaming', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('placement', models.CharField(choices=[('home', 'Главная'), ('catalog', 'Каталог'), ('detail', 'Карточка произведения')], max_length=12, verbose_name='Размещение')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=280, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='promotions/%Y/%m', verbose_name='Изображение')),
                ('target_url', models.URLField(verbose_name='Целевая ссылка')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Показывать с')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Показывать до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Партнёрский баннер',
                'verbose_name_plural': 'Партнёрские баннеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Адрес')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('level', models.CharField(choices=[('premium', 'Premium'), ('vip', 'VIP')], max_length=10, verbose_name='Уровень')),
                ('period', models.CharField(choices=[('month', 'Месяц'), ('year', 'Год')], default='month', max_length=10, verbose_name='Период')),
                ('price_minor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена в минимальных единицах')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для подключения')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['level', 'price_minor'],
            },
        ),
        migrations.CreateModel(
            name='ContentOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('kind', models.CharField(choices=[('rental', 'Аренда'), ('purchase', 'Покупка')], max_length=10, verbose_name='Тип')),
                ('price_minor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена в минимальных единицах')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('rental_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Срок аренды, часов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='streaming.videoasset', verbose_name='Видеоресурс')),
            ],
            options={
                'verbose_name': 'Коммерческое предложение',
                'verbose_name_plural': 'Коммерческие предложения',
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('source', models.CharField(choices=[('purchase', 'Покупка'), ('rental', 'Аренда'), ('promo', 'Промокод'), ('support', 'Поддержка')], max_length=12, verbose_name='Источник')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозвано')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='streaming.videoasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Право доступа',
                'verbose_name_plural': 'Права доступа',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Промокод состоит из 3–32 прописных латинских букв, цифр, дефисов или подчёркиваний.', regex='^[A-Z0-9][A-Z0-9_-]{2,31}$')], verbose_name='Код')),
                ('grant_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок доступа, дней')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит активаций')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promo_codes', to='streaming.videoasset', verbose_name='Видеоресурс')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promo_codes', to='billing.subscriptionplan', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='billing.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активация промокода',
                'verbose_name_plural': 'Активации промокодов',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('reward_granted_at', models.DateTimeField(blank=True, null=True, verbose_name='Награда выдана')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
            },
        ),
        migrations.CreateModel(
            name='ReferralProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('code', models.CharField(editable=False, max_length=16, unique=True, verbose_name='Реферальный код')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реферальный профиль',
                'verbose_name_plural': 'Реферальные профили',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('active', 'Активна'), ('canceled', 'Отменена'), ('expired', 'Истекла')], default='pending', max_length=10, verbose_name='Статус')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало оплаченного периода')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец оплаченного периода')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='Отменить по окончании периода')),
                ('provider', models.CharField(blank=True, max_length=32, verbose_name='Платёжный провайдер')),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255, verbose_name='Идентификатор подписки у провайдера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('yookassa', 'ЮKassa'), ('cloudpayments', 'CloudPayments')], max_length=20, verbose_name='Провайдер')),
                ('provider_payment_id', models.CharField(max_length=255, unique=True, verbose_name='Идентификатор платежа')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('pending', 'Ожидает подтверждения'), ('succeeded', 'Подтверждён'), ('failed', 'Неуспешен'), ('canceled', 'Отменён'), ('refunded', 'Возвращён')], default='created', max_length=10, verbose_name='Статус')),
                ('amount_minor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма в минимальных единицах')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Технические данные')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.contentoffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.subscription')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.AddConstraint(
            model_name='contentoffer',
            constraint=models.UniqueConstraint(fields=('asset', 'kind'), name='unique_content_offer_kind'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['user', 'asset', 'expires_at'], name='entitlement_access_idx'),
        ),
        migrations.AddConstraint(
            model_name='promoredemption',
            constraint=models.UniqueConstraint(fields=('promo_code', 'user'), name='unique_promo_redemption'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status', '-created_at'], name='payment_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status', 'current_period_end'], name='subscription_access_idx'),
        ),
    ]
