# Generated by Django 5.1.15 on 2026-07-29 09:41

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, upload_to='promotions/%Y/%m', validators=[apps.core.validators.validate_image_file], verbose_name='Изображение'),
        ),
    ]
