# Generated by Django 5.2.16 on 2026-07-17 08:39

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/%Y/%m', validators=[apps.core.validators.validate_image_file], verbose_name='Аватар'),
        ),
    ]
