# Generated by Django 5.2.16 on 2026-07-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_subscription',
            field=models.TextField(blank=True, default='', verbose_name='Push-подписка'),
        ),
    ]
