"""
Тестовые данные для наполнения каталога.

Вынесены из команд seed_catalog и seed_content, чтобы логика осталась
короткой и читаемой: код отдельно, данные отдельно.

Что чем является с точки зрения авторского права:
- названия, годы, страны, длительность, жанры — общеизвестные факты;
- имена актёров, режиссёров, сценаристов и роли, которые они сыграли, —
  тоже факты, они никому не принадлежат;
- описания и слоганы написаны специально для этого проекта, чужой текст
  (синопсисы Кинопоиска, IMDb и т.п.) не копируется;
- оценки — демонстрационные, собраны из выдуманных отзывов ниже.

Постеры и трейлеры файлами не заполняем: их рисует generate_placeholder_art
или загружает редактор через админку.
"""

# (название, адрес латиницей)
GENRES = [
    ("Анимация", "animaciya"),
    ("Биография", "biografiya"),
    ("Боевик", "boevik"),
    ("Детектив", "detektiv"),
    ("Документальный", "dokumentalnyy"),
    ("Драма", "drama"),
    ("Комедия", "komediya"),
    ("Криминал", "kriminal"),
    ("Мелодрама", "melodrama"),
    ("Приключения", "priklyucheniya"),
    ("Триллер", "triller"),
    ("Ужасы", "uzhasy"),
    ("Фантастика", "fantastika"),
    ("Фэнтези", "fentezi"),
]

COUNTRIES = [
    ("Великобритания", "velikobritaniya"),
    ("Германия", "germaniya"),
    ("Индия", "indiya"),
    ("Испания", "ispaniya"),
    ("Италия", "italiya"),
    ("Канада", "kanada"),
    ("Россия", "rossiya"),
    ("США", "ssha"),
    ("Франция", "franciya"),
    ("Южная Корея", "yuzhnaya-koreya"),
    ("Япония", "yaponiya"),
]

TITLES = [
    {
        "name": "Начало",
        "original_name": "Inception",
        "slug": "nachalo-2010",
        "type": "movie",
        "release_year": 2010,
        "duration_minutes": 148,
        "age_rating": "12+",
        "genres": ["Фантастика", "Боевик", "Триллер"],
        "countries": ["США", "Великобритания"],
        "short_description": "Сон во сне, где украсть можно даже чужую мысль.",
        "description": "Фантастический триллер о команде, которая работает внутри чужих снов. Фильм известен многослойной структурой повествования и практическими спецэффектами.",
        "trailer_url": "https://www.youtube.com/watch?v=F977gw0ecwY",
        "voice_acting": "dubbed",
        "views_count": 12840,
        "quality": "Blu-ray",
        "status": "published",
    },
    {
        "name": "Паразиты",
        "original_name": "기생충",
        "slug": "parazity-2019",
        "type": "movie",
        "release_year": 2019,
        "duration_minutes": 132,
        "age_rating": "18+",
        "genres": ["Драма", "Триллер", "Комедия"],
        "countries": ["Южная Корея"],
        "short_description": "Две семьи, одна лестница — и пропасть между этажами.",
        "description": "Социальная драма о двух семьях из разных слоёв общества. Первый неанглоязычный фильм, получивший главный «Оскар».",
        "trailer_url": "https://www.youtube.com/watch?v=Pf8ymf6HYkc",
        "quality": "Blu-ray",
        "status": "published",
    },
    {
        "name": "Интерстеллар",
        "original_name": "Interstellar",
        "slug": "interstellar-2014",
        "type": "movie",
        "release_year": 2014,
        "duration_minutes": 169,
        "age_rating": "12+",
        "genres": ["Фантастика", "Драма", "Приключения"],
        "countries": ["США", "Великобритания"],
        "short_description": "Чтобы спасти Землю, придётся её покинуть.",
        "description": "Космическая экспедиция ищет новый дом для человечества. При работе над фильмом консультировал физик-теоретик Кип Торн.",
        "trailer_url": "https://www.youtube.com/watch?v=5DKSiMFHHxY",
        "voice_acting": "dubbed",
        "views_count": 11320,
        "quality": "Blu-ray",
        "status": "published",
    },
    {
        "name": "ВАЛЛ·И",
        "original_name": "WALL·E",
        "slug": "vall-i-2008",
        "type": "cartoon",
        "release_year": 2008,
        "duration_minutes": 98,
        "age_rating": "6+",
        "genres": ["Анимация", "Фантастика", "Приключения"],
        "countries": ["США"],
        "short_description": "Последний робот на Земле нашёл то, ради чего стоит жить.",
        "description": "Робот-уборщик остался один на покинутой людьми Земле и однажды встречает гостью с неба. Полнометражная анимация студии Pixar, отмеченная «Оскаром».",
        "voice_acting": "dubbed",
        "views_count": 9860,
        "quality": "Blu-ray",
        "status": "published",
    },
    {
        "name": "Вечерний Ургант",
        "original_name": "Evening Urgant",
        "slug": "vecherniy-urgant-2012",
        "type": "tv_show",
        "release_year": 2012,
        "duration_minutes": 45,
        "age_rating": "16+",
        "genres": ["Комедия"],
        "countries": ["Россия"],
        "short_description": "Гости, шутки и то, о чём говорит вся страна.",
        "description": "Вечернее ток-шоу с гостьями из мира кино, музыки и спорта. Демонстрационная запись: выпуски не заполнены.",
        "views_count": 3100,
        "quality": "WEB-DL",
        "status": "published",
    },
    {
        "name": "Прибытие",
        "original_name": "Arrival",
        "slug": "pribytie-2016",
        "type": "movie",
        "release_year": 2016,
        "duration_minutes": 116,
        "age_rating": "12+",
        "genres": ["Фантастика", "Драма"],
        "countries": ["США", "Канада"],
        "short_description": "Иногда первый контакт — это вопрос перевода.",
        "description": "Лингвист пытается наладить контакт с инопланетной цивилизацией. Фантастика, построенная вокруг языка, а не оружия.",
        "trailer_url": "https://www.youtube.com/watch?v=3SLTv9kP6NA",
        "quality": "Blu-ray",
        "status": "published",
    },
    {
        "name": "Достать ножи",
        "original_name": "Knives Out",
        "slug": "dostat-nozhi-2019",
        "type": "movie",
        "release_year": 2019,
        "duration_minutes": 130,
        "age_rating": "16+",
        "genres": ["Детектив", "Комедия", "Криминал"],
        "countries": ["США"],
        "short_description": "Наследство, которое стоило кому-то жизни.",
        "description": "Классический детектив о расследовании смерти писателя в кругу его наследников.",
        "quality": "Blu-ray",
        "status": "published",
    },
    {
        "name": "Амели",
        "original_name": "Le Fabuleux Destin d'Amélie Poulain",
        "slug": "ameli-2001",
        "type": "movie",
        "release_year": 2001,
        "duration_minutes": 122,
        "age_rating": "16+",
        "genres": ["Мелодрама", "Комедия"],
        "countries": ["Франция", "Германия"],
        "short_description": "Маленькие радости, которые она дарит незаметно.",
        "description": "История парижанки, которая незаметно устраивает счастье окружающих. Фильм известен насыщенной цветовой палитрой.",
        "quality": "Blu-ray",
        "status": "published",
    },
    {
        "name": "Бегущий по лезвию 2049",
        "original_name": "Blade Runner 2049",
        "slug": "begushchiy-po-lezviyu-2049",
        "type": "movie",
        "release_year": 2017,
        "duration_minutes": 164,
        "age_rating": "16+",
        "genres": ["Фантастика", "Драма", "Детектив"],
        "countries": ["США", "Великобритания", "Канада"],
        "short_description": "Что делает человека настоящим, если его собрали?",
        "description": "Продолжение фантастической антиутопии 1982 года. Отмечен «Оскаром» за операторскую работу.",
        "quality": "Blu-ray",
        "status": "published",
    },
    {
        "name": "Криминальное чтиво",
        "original_name": "Pulp Fiction",
        "slug": "kriminalnoe-chtivo-1994",
        "type": "movie",
        "release_year": 1994,
        "duration_minutes": 154,
        "age_rating": "18+",
        "genres": ["Криминал", "Драма"],
        "countries": ["США"],
        "short_description": "Пять историй, в которых всё идёт не по плану.",
        "description": "Несколько криминальных историй, рассказанных вперемешку. Фильм заметно повлиял на кино девяностых.",
        "trailer_url": "https://www.youtube.com/watch?v=tGpTpVyI_OQ",
        "quality": "Blu-ray",
        "status": "published",
    },
    {
        "name": "Тьма",
        "original_name": "Dark",
        "slug": "tma-2017",
        "type": "series",
        "release_year": 2017,
        "duration_minutes": 55,
        "age_rating": "16+",
        "genres": ["Фантастика", "Триллер", "Детектив"],
        "countries": ["Германия"],
        "short_description": "В этом городке время идёт по кругу.",
        "description": "Исчезновение ребёнка в небольшом городке связывает судьбы четырёх семей на протяжении десятилетий. Три сезона.",
        "quality": "WEB-DL",
        "status": "published",
    },
    {
        "name": "Чернобыль",
        "original_name": "Chernobyl",
        "slug": "chernobyl-2019",
        "type": "series",
        "release_year": 2019,
        "duration_minutes": 60,
        "age_rating": "18+",
        "genres": ["Драма", "Биография"],
        "countries": ["США", "Великобритания"],
        "short_description": "Реактор замолчал, но правду ещё предстоит услышать.",
        "description": "Мини-сериал о катастрофе 1986 года и работе ликвидаторов. Пять серий.",
        "trailer_url": "https://www.youtube.com/watch?v=sK7kqPhPqpo",
        "voice_acting": "lostfilm",
        "views_count": 14580,
        "latest_episode_info": "1 сезон 5 серия",
        "quality": "WEB-DL",
        "status": "published",
    },
    {
        "name": "Во все тяжкие",
        "original_name": "Breaking Bad",
        "slug": "vo-vse-tyazhkie-2008",
        "type": "series",
        "release_year": 2008,
        "duration_minutes": 47,
        "age_rating": "18+",
        "genres": ["Криминал", "Драма", "Триллер"],
        "countries": ["США"],
        "short_description": "От учителя химии до имени, которого боятся.",
        "description": "Школьный учитель химии постепенно превращается в преступника. Пять сезонов.",
        "trailer_url": "https://www.youtube.com/watch?v=HhesaQXLuRY",
        "voice_acting": "lostfilm",
        "views_count": 16740,
        "latest_episode_info": "5 сезон 16 серия",
        "quality": "WEB-DL",
        "status": "published",
    },
    {
        "name": "Игра в кальмара",
        "original_name": "오징어 게임",
        "slug": "igra-v-kalmara-2021",
        "type": "series",
        "release_year": 2021,
        "duration_minutes": 55,
        "age_rating": "18+",
        "genres": ["Триллер", "Драма"],
        "countries": ["Южная Корея"],
        "short_description": "456 игроков, один приз и никакого милосердия.",
        "description": "Должники соглашаются участвовать в смертельно опасных играх ради денежного приза.",
        "trailer_url": "https://www.youtube.com/watch?v=fNKyxkIuKSI",
        "voice_acting": "hdrezka",
        "views_count": 13210,
        "quality": "WEB-DL",
        "status": "published",
    },
    {
        "name": "Настоящий детектив",
        "original_name": "True Detective",
        "slug": "nastoyashchiy-detektiv-2014",
        "type": "series",
        "release_year": 2014,
        "duration_minutes": 55,
        "age_rating": "18+",
        "genres": ["Криминал", "Детектив", "Драма"],
        "countries": ["США"],
        "short_description": "Двое напарников идут по следу, который тянется годами.",
        "description": "Антология: каждый сезон рассказывает отдельное расследование с новыми героями.",
        "quality": "WEB-DL",
        "status": "published",
    },
    # Две записи оставлены черновиками намеренно: на них будет видно,
    # что каталог показывает посетителям только опубликованное.
    {
        "name": "Дюна: Часть вторая",
        "original_name": "Dune: Part Two",
        "slug": "dyuna-chast-vtoraya-2024",
        "type": "movie",
        "release_year": 2024,
        "duration_minutes": 166,
        "age_rating": "12+",
        "genres": ["Фантастика", "Приключения", "Драма"],
        "countries": ["США", "Канада"],
        "short_description": "Месть, пророчество и пустыня, что помнит всё.",
        "description": "Продолжение экранизации романа Фрэнка Герберта.",
        "trailer_url": "https://www.youtube.com/watch?v=Way9Dexny3w",
        "quality": "Blu-ray",
        "status": "draft",
    },
    {
        "name": "Корона",
        "original_name": "The Crown",
        "slug": "korona-2016",
        "type": "series",
        "release_year": 2016,
        "duration_minutes": 58,
        "age_rating": "16+",
        "genres": ["Драма", "Биография"],
        "countries": ["Великобритания"],
        "short_description": "Корона тяжелее, чем кажется со стороны.",
        "description": "Историческая драма о британской монархии второй половины XX века.",
        "quality": "WEB-DL",
        "status": "draft",
    },
]

# ---------------------------------------------------------------------------
# Съёмочная группа. Имена и роли — факты, их можно перечислять свободно.
# ---------------------------------------------------------------------------

# (имя, адрес латиницей). Один человек — одна запись, даже если он снялся
# в нескольких проектах: так на его странице собирается фильмография.
PERSONS = [
    # Режиссёры и сценаристы
    ("Кристофер Нолан", "kristofer-nolan"),
    ("Джонатан Нолан", "dzhonatan-nolan"),
    ("Пон Джун-хо", "pon-dzhun-kho"),
    ("Хан Джин-вон", "khan-dzhin-von"),
    ("Эндрю Стэнтон", "endryu-stenton"),
    ("Дени Вильнёв", "deni-vilnev"),
    ("Эрик Хайссерер", "erik-khaysserer"),
    ("Райан Джонсон", "rayan-dzhonson"),
    ("Жан-Пьер Жёне", "zhan-per-zhene"),
    ("Квентин Тарантино", "kventin-tarantino"),
    ("Баран бо Одар", "baran-bo-odar"),
    ("Янтье Фризе", "yante-frize"),
    ("Крэйг Мэйзин", "kreyg-meyzin"),
    ("Йохан Ренк", "yokhan-renk"),
    ("Винс Гиллиган", "vins-gilligan"),
    ("Хван Дон-хёк", "khvan-don-khyok"),
    ("Ник Пиццолатто", "nik-piccolatto"),
    ("Кэри Фукунага", "keri-fukunaga"),
    # Актёры
    ("Леонардо ДиКаприо", "leonardo-dikaprio"),
    ("Джозеф Гордон-Левитт", "dzhozef-gordon-levitt"),
    ("Эллиот Пейдж", "elliot-peydzh"),
    ("Том Харди", "tom-khardi"),
    ("Кэн Ватанабэ", "ken-vatanabe"),
    ("Сон Кан-хо", "son-kan-kho"),
    ("Ли Сон-гюн", "li-son-gyun"),
    ("Чо Ё-джон", "cho-yo-dzhon"),
    ("Чхве У-щик", "chkhve-u-shchik"),
    ("Пак Со-дам", "pak-so-dam"),
    ("Мэттью Макконахи", "mettyu-makkonakhi"),
    ("Энн Хэтэуэй", "enn-kheteuey"),
    ("Джессика Честейн", "dzhessika-chesteyn"),
    ("Майкл Кейн", "maykl-keyn"),
    ("Эми Адамс", "emi-adams"),
    ("Джереми Реннер", "dzheremi-renner"),
    ("Форест Уитакер", "forest-uitaker"),
    ("Дэниел Крэйг", "deniel-kreyg"),
    ("Ана де Армас", "ana-de-armas"),
    ("Крис Эванс", "kris-evans"),
    ("Джейми Ли Кёртис", "dzheymi-li-kyortis"),
    ("Одри Тоту", "odri-totu"),
    ("Матьё Кассовиц", "mate-kassovic"),
    ("Райан Гослинг", "rayan-gosling"),
    ("Харрисон Форд", "kharrison-ford"),
    ("Джон Траволта", "dzhon-travolta"),
    ("Сэмюэл Л. Джексон", "semyuel-l-dzhekson"),
    ("Ума Турман", "uma-turman"),
    ("Брюс Уиллис", "bryus-uillis"),
    ("Луис Хофманн", "luis-khofmann"),
    ("Джаред Харрис", "dzhared-kharris"),
    ("Стеллан Скарсгард", "stellan-skarsgard"),
    ("Эмили Уотсон", "emili-uotson"),
    ("Брайан Крэнстон", "brayan-krenston"),
    ("Аарон Пол", "aaron-pol"),
    ("Анна Ганн", "anna-gann"),
    ("Ли Джон-джэ", "li-dzhon-dzhe"),
    ("Пак Хэ-су", "pak-khe-su"),
    ("Чон Хо-ён", "chon-kho-yon"),
    ("Вуди Харрельсон", "vudi-kharrelson"),
    # Композиторы и операторы
    ("Ханс Циммер", "khans-cimmer"),
    ("Томас Ньюман", "tomas-nyuman"),
    ("Ян Тьерсен", "yan-tersen"),
    ("Роджер Дикинс", "rodzher-dikins"),
    ("Йоханн Йоханнссон", "yokhann-yokhannsson"),
]

# Адрес фильма -> список участий.
# (адрес персоны, роль, имя персонажа, порядок). Роль — значение из
# Participation.Role: director, actor, writer, producer, composer, operator.
CREDITS = {
    "nachalo-2010": [
        ("kristofer-nolan", "director", "", 1),
        ("leonardo-dikaprio", "actor", "Дом Кобб", 2),
        ("dzhozef-gordon-levitt", "actor", "Артур", 3),
        ("elliot-peydzh", "actor", "Ариадна", 4),
        ("tom-khardi", "actor", "Имс", 5),
        ("ken-vatanabe", "actor", "Сайто", 6),
        ("kristofer-nolan", "writer", "", 7),
        ("khans-cimmer", "composer", "", 8),
    ],
    "parazity-2019": [
        ("pon-dzhun-kho", "director", "", 1),
        ("son-kan-kho", "actor", "Ки-тэк", 2),
        ("li-son-gyun", "actor", "Пак Дон-ик", 3),
        ("cho-yo-dzhon", "actor", "Ён-гё", 4),
        ("chkhve-u-shchik", "actor", "Ки-у", 5),
        ("pak-so-dam", "actor", "Ки-джон", 6),
        ("khan-dzhin-von", "writer", "", 7),
    ],
    "interstellar-2014": [
        ("kristofer-nolan", "director", "", 1),
        ("mettyu-makkonakhi", "actor", "Купер", 2),
        ("enn-kheteuey", "actor", "Амелия Бранд", 3),
        ("dzhessika-chesteyn", "actor", "Мёрф", 4),
        ("maykl-keyn", "actor", "профессор Бранд", 5),
        ("dzhonatan-nolan", "writer", "", 6),
        ("khans-cimmer", "composer", "", 7),
    ],
    "vall-i-2008": [
        ("endryu-stenton", "director", "", 1),
        ("endryu-stenton", "writer", "", 2),
        ("tomas-nyuman", "composer", "", 3),
    ],
    "pribytie-2016": [
        ("deni-vilnev", "director", "", 1),
        ("emi-adams", "actor", "Луиза Бэнкс", 2),
        ("dzheremi-renner", "actor", "Иэн Доннелли", 3),
        ("forest-uitaker", "actor", "полковник Вебер", 4),
        ("erik-khaysserer", "writer", "", 5),
        ("yokhann-yokhannsson", "composer", "", 6),
    ],
    "dostat-nozhi-2019": [
        ("rayan-dzhonson", "director", "", 1),
        ("deniel-kreyg", "actor", "Бенуа Блан", 2),
        ("ana-de-armas", "actor", "Марта Кабрера", 3),
        ("kris-evans", "actor", "Рэнсом", 4),
        ("dzheymi-li-kyortis", "actor", "Линда", 5),
        ("rayan-dzhonson", "writer", "", 6),
    ],
    "ameli-2001": [
        ("zhan-per-zhene", "director", "", 1),
        ("odri-totu", "actor", "Амели Пулен", 2),
        ("mate-kassovic", "actor", "Нино", 3),
        ("yan-tersen", "composer", "", 4),
    ],
    "begushchiy-po-lezviyu-2049": [
        ("deni-vilnev", "director", "", 1),
        ("rayan-gosling", "actor", "Кей", 2),
        ("kharrison-ford", "actor", "Рик Декард", 3),
        ("ana-de-armas", "actor", "Джой", 4),
        ("rodzher-dikins", "operator", "", 5),
    ],
    "kriminalnoe-chtivo-1994": [
        ("kventin-tarantino", "director", "", 1),
        ("dzhon-travolta", "actor", "Винсент Вега", 2),
        ("semyuel-l-dzhekson", "actor", "Джулс Уинфилд", 3),
        ("uma-turman", "actor", "Миа Уоллес", 4),
        ("bryus-uillis", "actor", "Бутч", 5),
        ("kventin-tarantino", "writer", "", 6),
    ],
    "tma-2017": [
        ("baran-bo-odar", "director", "", 1),
        ("luis-khofmann", "actor", "Йонас Канвальд", 2),
        ("yante-frize", "writer", "", 3),
    ],
    "chernobyl-2019": [
        ("yokhan-renk", "director", "", 1),
        ("dzhared-kharris", "actor", "Валерий Легасов", 2),
        ("stellan-skarsgard", "actor", "Борис Щербина", 3),
        ("emili-uotson", "actor", "Ульяна Хомюк", 4),
        ("kreyg-meyzin", "writer", "", 5),
    ],
    "vo-vse-tyazhkie-2008": [
        ("vins-gilligan", "director", "", 1),
        ("brayan-krenston", "actor", "Уолтер Уайт", 2),
        ("aaron-pol", "actor", "Джесси Пинкман", 3),
        ("anna-gann", "actor", "Скайлер Уайт", 4),
        ("vins-gilligan", "writer", "", 5),
    ],
    "igra-v-kalmara-2021": [
        ("khvan-don-khyok", "director", "", 1),
        ("li-dzhon-dzhe", "actor", "Сон Ги-хун", 2),
        ("pak-khe-su", "actor", "Чо Сан-у", 3),
        ("chon-kho-yon", "actor", "Кан Сэ-бёк", 4),
        ("khvan-don-khyok", "writer", "", 5),
    ],
    "nastoyashchiy-detektiv-2014": [
        ("keri-fukunaga", "director", "", 1),
        ("mettyu-makkonakhi", "actor", "Раст Коул", 2),
        ("vudi-kharrelson", "actor", "Марти Харт", 3),
        ("nik-piccolatto", "writer", "", 4),
    ],
}

# Ручные «похожие»: связи, которых не видно по одним жанрам (тот же режиссёр,
# та же интонация). symmetrical=False, поэтому связь указывается с обеих сторон,
# если нужна взаимность.
RELATED = {
    "nachalo-2010": ["interstellar-2014", "begushchiy-po-lezviyu-2049"],
    "interstellar-2014": ["nachalo-2010", "pribytie-2016"],
    "pribytie-2016": ["begushchiy-po-lezviyu-2049", "interstellar-2014"],
    "begushchiy-po-lezviyu-2049": ["pribytie-2016", "nachalo-2010"],
    "nastoyashchiy-detektiv-2014": ["vo-vse-tyazhkie-2008"],
}

# ---------------------------------------------------------------------------
# Подборки — витрина главной страницы.
# ---------------------------------------------------------------------------

COLLECTIONS = [
    {
        "name": "Умная фантастика",
        "slug": "umnaya-fantastika",
        "description": "Истории, где идея важнее взрыва: пространство, время и язык как главные герои.",
        "is_featured": True,
        "titles": [
            "interstellar-2014",
            "nachalo-2010",
            "pribytie-2016",
            "begushchiy-po-lezviyu-2049",
        ],
    },
    {
        "name": "Криминал и напряжение",
        "slug": "kriminal-i-napryazhenie",
        "description": "Там, где одно решение меняет всё, а напряжение держится до последней сцены.",
        "is_featured": True,
        "titles": [
            "vo-vse-tyazhkie-2008",
            "parazity-2019",
            "kriminalnoe-chtivo-1994",
            "nastoyashchiy-detektiv-2014",
            "dostat-nozhi-2019",
        ],
    },
    {
        "name": "С чего начать",
        "slug": "s-chego-nachat",
        "description": "Короткий список для знакомства с каталогом: разные жанры, каждый — без осечки.",
        "is_featured": True,
        "titles": [
            "igra-v-kalmara-2021",
            "dostat-nozhi-2019",
            "interstellar-2014",
            "vo-vse-tyazhkie-2008",
        ],
    },
    {
        "name": "Награды и признание",
        "slug": "nagrady-i-priznanie",
        "description": "Фильмы и сериалы, отмеченные главными премиями и критикой.",
        "is_featured": False,
        "titles": [
            "parazity-2019",
            "chernobyl-2019",
            "vall-i-2008",
            "ameli-2001",
        ],
    },
]

# ---------------------------------------------------------------------------
# Демо-зрители и их отзывы. Отзывы дают оценкам реальную основу: рейтинг
# считается из них сигналами, а не проставляется руками (иначе фоновая
# задача-пересчёт обнулила бы его). Тексты — оригинальные и короткие.
# ---------------------------------------------------------------------------

# (никнейм, почта). Пароль этим аккаунтам не нужен: они только оставляют отзывы.
DEMO_USERS = [
    ("kinoved", "kinoved@demo.lumibox"),
    ("mira_v", "mira@demo.lumibox"),
    ("night_owl", "nightowl@demo.lumibox"),
    ("polina87", "polina@demo.lumibox"),
    ("sergey_d", "sergey@demo.lumibox"),
    ("lena_k", "lena@demo.lumibox"),
    ("the_critic", "critic@demo.lumibox"),
    ("maxx", "maxx@demo.lumibox"),
    ("olga_r", "olga@demo.lumibox"),
    ("denis_kino", "denis@demo.lumibox"),
]

# Адрес фильма -> список отзывов (оценка, текст). i-й отзыв оставляет i-й
# пользователь из DEMO_USERS, поэтому длина списка не больше числа демо-зрителей.
# Пустой текст — обычное дело: многие ставят оценку, не расписывая мнение.
REVIEWS = {
    "nachalo-2010": [
        (9, "Пересматриваю раз в год и каждый раз замечаю новую деталь."),
        (10, "Финал с волчком до сих пор обсуждаем всей семьёй."),
        (8, ""),
        (9, ""),
        (7, "Сильно, но во второй половине немного теряешь нить."),
        (9, ""),
    ],
    "parazity-2019": [
        (10, "Начинается как комедия, а заканчивается так, что мурашки."),
        (9, ""),
        (10, ""),
        (8, "Каждый кадр продуман до мелочей."),
        (9, ""),
    ],
    "interstellar-2014": [
        (10, "Сцена со стыковкой под музыку Циммера — это что-то невероятное."),
        (9, ""),
        (8, ""),
        (10, "Плакал на моменте с видеосообщениями. Редкий случай."),
        (9, ""),
        (7, ""),
    ],
    "vall-i-2008": [
        (10, "Лучшее, что сделала анимация. Показываю детям и смотрю сам."),
        (9, ""),
        (10, ""),
        (8, ""),
    ],
    "pribytie-2016": [
        (9, "Фантастика, где оружие — это слова. Освежает."),
        (8, ""),
        (9, ""),
        (7, "Красиво, но требует терпения."),
    ],
    "dostat-nozhi-2019": [
        (8, "Умный детектив, который не забыл про юмор."),
        (9, ""),
        (8, ""),
        (7, ""),
    ],
    "ameli-2001": [
        (9, "Тёплый фильм, после которого хочется делать людям приятное."),
        (8, ""),
        (9, ""),
    ],
    "begushchiy-po-lezviyu-2049": [
        (9, "Картинка — произведение искусства. Дикинс заслужил каждую награду."),
        (8, ""),
        (7, "Долго, но атмосфера того стоит."),
        (9, ""),
    ],
    "kriminalnoe-chtivo-1994": [
        (10, "Диалоги можно растаскивать на цитаты бесконечно."),
        (9, ""),
        (8, ""),
        (9, ""),
    ],
    "tma-2017": [
        (9, "Без блокнота на третьей серии не разобраться — и это прекрасно."),
        (8, ""),
        (9, ""),
    ],
    "chernobyl-2019": [
        (10, "Пять серий, от которых невозможно оторваться."),
        (10, ""),
        (9, ""),
        (9, "Тяжело смотреть, но нужно."),
    ],
    "vo-vse-tyazhkie-2008": [
        (10, "Эталон того, как персонаж меняется от серии к серии."),
        (10, ""),
        (9, ""),
        (10, ""),
        (8, ""),
    ],
    "igra-v-kalmara-2021": [
        (8, "Затягивает, хотя местами предсказуемо."),
        (9, ""),
        (7, ""),
        (8, ""),
    ],
    "nastoyashchiy-detektiv-2014": [
        (10, "Макконахи в первом сезоне — отдельный вид искусства."),
        (9, ""),
        (8, ""),
        (9, ""),
    ],
}
