# Generated by Django 5.2.16 on 2026-07-16 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Часть ссылки латиницей, например: dokumentalnyy', max_length=120, unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Часть ссылки латиницей, например: dokumentalnyy', max_length=120, unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('type', models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал')], default='movie', max_length=10, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('original_name', models.CharField(blank=True, help_text='Название на языке оригинала', max_length=255, verbose_name='Оригинальное название')),
                ('slug', models.SlugField(help_text='Часть ссылки латиницей. В админке заполнится сама.', max_length=280, unique=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('release_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)], verbose_name='Год выпуска')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Для сериала — длительность одной серии', null=True, verbose_name='Длительность, мин')),
                ('age_rating', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], max_length=3, verbose_name='Возрастной рейтинг')),
                ('poster', models.ImageField(blank=True, help_text='Вертикальное изображение', upload_to='posters/%Y/%m', verbose_name='Постер')),
                ('trailer_url', models.URLField(blank=True, help_text='Ссылка на YouTube', verbose_name='Ссылка на трейлер')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=10, verbose_name='Статус')),
                ('published_at', models.DateTimeField(blank=True, help_text='Проставляется при первой публикации', null=True, verbose_name='Дата публикации')),
                ('countries', models.ManyToManyField(blank=True, related_name='titles', to='catalog.country', verbose_name='Страны')),
                ('genres', models.ManyToManyField(blank=True, related_name='titles', to='catalog.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Фильм или сериал',
                'verbose_name_plural': 'Фильмы и сериалы',
                'ordering': ['-release_year', 'name'],
                'indexes': [models.Index(fields=['status', 'type'], name='title_status_type_idx'), models.Index(fields=['-release_year'], name='title_year_idx')],
            },
        ),
    ]
