# Generated by Django 5.2.16 on 2026-07-16 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Если пусто — возьмётся название', max_length=70, verbose_name='SEO-заголовок')),
                ('meta_description', models.CharField(blank=True, help_text='Если пусто — возьмётся начало описания', max_length=160, verbose_name='SEO-описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, help_text='Горизонтальное изображение', upload_to='collections/%Y/%m', verbose_name='Обложка')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('is_featured', models.BooleanField(default=False, help_text='Подборка появится в отдельном блоке главной страницы', verbose_name='Показывать на главной')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Подборка',
                'verbose_name_plural': 'Подборки',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='title',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Если пусто — возьмётся начало описания', max_length=160, verbose_name='SEO-описание'),
        ),
        migrations.AddField(
            model_name='title',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Если пусто — возьмётся название', max_length=70, verbose_name='SEO-заголовок'),
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.collection', verbose_name='Подборка')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='catalog.title', verbose_name='Фильм или сериал')),
            ],
            options={
                'verbose_name': 'Запись подборки',
                'verbose_name_plural': 'Записи подборки',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='titles',
            field=models.ManyToManyField(blank=True, related_name='collections', through='catalog.CollectionItem', to='catalog.title', verbose_name='Фильмы и сериалы'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('original_name', models.CharField(blank=True, max_length=150, verbose_name='Имя в оригинале')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='Адрес')),
                ('photo', models.ImageField(blank=True, upload_to='persons/%Y/%m', verbose_name='Фото')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='person_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Режиссёр'), ('actor', 'Актёр'), ('writer', 'Сценарист'), ('producer', 'Продюсер'), ('composer', 'Композитор'), ('operator', 'Оператор')], default='actor', max_length=20, verbose_name='Роль')),
                ('character', models.CharField(blank=True, help_text='Только для актёров', max_length=150, verbose_name='Имя персонажа')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='catalog.title', verbose_name='Фильм или сериал')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='catalog.person', verbose_name='Персона')),
            ],
            options={
                'verbose_name': 'Участие',
                'verbose_name_plural': 'Участие в проектах',
                'ordering': ['order', 'person__name'],
            },
        ),
        migrations.AddField(
            model_name='title',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='titles', through='catalog.Participation', to='catalog.person', verbose_name='Съёмочная группа'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'title'), name='unique_collection_item'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['is_published', 'order'], name='collection_pub_order_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['title', 'role', 'order'], name='participation_title_idx'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('title', 'person', 'role'), name='unique_participation'),
        ),
    ]
