# Generated by Django 5.2.16 on 2026-07-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_collection_title_meta_description_title_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating_average',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=3, null=True, verbose_name='Средняя оценка'),
        ),
        migrations.AddField(
            model_name='title',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Число оценок'),
        ),
    ]
