# Generated by Django 5.2.16 on 2026-07-17 08:39

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_title_rating_average_title_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cover',
            field=models.ImageField(blank=True, help_text='Горизонтальное изображение, до 5 МБ', upload_to='collections/%Y/%m', validators=[apps.core.validators.validate_image_file], verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to='persons/%Y/%m', validators=[apps.core.validators.validate_image_file], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster',
            field=models.ImageField(blank=True, help_text='Вертикальное изображение, до 5 МБ', upload_to='posters/%Y/%m', validators=[apps.core.validators.validate_image_file], verbose_name='Постер'),
        ),
    ]
