# Generated by Django 5.2.16 on 2026-07-17 20:33

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_collection_cover_alter_person_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='backdrop',
            field=models.ImageField(blank=True, help_text='Широкое горизонтальное изображение (16:9) для шапки страницы фильма. Необязательно.', upload_to='backdrops/%Y/%m', validators=[apps.core.validators.validate_image_file], verbose_name='Фон страницы'),
        ),
        migrations.AddField(
            model_name='title',
            name='trailer_file',
            field=models.FileField(blank=True, help_text='Своё видео (mp4, webm, ogg). Оставьте пустым, если указываете ссылку.', upload_to='trailers/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg'])], verbose_name='Видеофайл трейлера'),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster',
            field=models.ImageField(blank=True, help_text='Вертикальное изображение (2:3), до 5 МБ. Обложка карточки в каталоге.', upload_to='posters/%Y/%m', validators=[apps.core.validators.validate_image_file], verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='title',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, Rutube и т.п. Оставьте пустым, если загружаете свой видеофайл.', verbose_name='Ссылка на трейлер'),
        ),
    ]
