# Generated by Django 5.2.16 on 2026-07-18 18:07

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_title_backdrop_title_trailer_file_alter_title_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='logo',
            field=models.ImageField(blank=True, help_text='Название фильма картинкой на прозрачном фоне (PNG). Показывается в шапке вместо текста.', upload_to='logos/%Y/%m', validators=[apps.core.validators.validate_image_file], verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='title',
            name='related_titles',
            field=models.ManyToManyField(blank=True, help_text='Если пусто — похожее подберётся автоматически по совпадению жанров.', related_name='related_to', to='catalog.title', verbose_name='Похожие вручную'),
        ),
        migrations.AddField(
            model_name='title',
            name='release_date',
            field=models.DateField(blank=True, help_text='Точная дата премьеры, если известна. Год выше обязателен в любом случае.', null=True, verbose_name='Дата выхода'),
        ),
        migrations.AddField(
            model_name='title',
            name='short_description',
            field=models.CharField(blank=True, help_text='Одна фраза для карточки и баннера. Если пусто — возьмётся начало описания.', max_length=200, verbose_name='Короткое описание'),
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Горизонтальный кадр, до 5 МБ', upload_to='frames/%Y/%m', validators=[apps.core.validators.validate_image_file], verbose_name='Кадр')),
                ('caption', models.CharField(blank=True, help_text='Необязательно. Используется как alt-текст для незрячих.', max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='catalog.title', verbose_name='Фильм или сериал')),
            ],
            options={
                'verbose_name': 'Кадр',
                'verbose_name_plural': 'Кадры',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['title', 'order'], name='frame_title_order_idx')],
            },
        ),
    ]
