# Generated by Django 5.1.15 on 2026-07-23 15:26

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_title_logo_title_related_titles_title_release_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Если пусто — возьмётся название', max_length=70, verbose_name='SEO-заголовок')),
                ('meta_description', models.CharField(blank=True, help_text='Если пусто — возьмётся начало описания', max_length=160, verbose_name='SEO-описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, upload_to='awards/%Y/%m', validators=[apps.core.validators.validate_image_file], verbose_name='Логотип')),
                ('website', models.URLField(blank=True, verbose_name='Официальный сайт')),
            ],
            options={
                'verbose_name': 'Премия',
                'verbose_name_plural': 'Премии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Если пусто — возьмётся название', max_length=70, verbose_name='SEO-заголовок')),
                ('meta_description', models.CharField(blank=True, help_text='Если пусто — возьмётся начало описания', max_length=160, verbose_name='SEO-описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, upload_to='studios/%Y/%m', validators=[apps.core.validators.validate_image_file], verbose_name='Логотип')),
                ('website', models.URLField(blank=True, verbose_name='Официальный сайт')),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='title',
            name='studios',
            field=models.ManyToManyField(blank=True, related_name='titles', to='catalog.studio', verbose_name='Студии'),
        ),
        migrations.CreateModel(
            name='TitleAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Год')),
                ('category', models.CharField(max_length=180, verbose_name='Номинация')),
                ('result', models.CharField(choices=[('nominee', 'Номинация'), ('winner', 'Победа')], default='nominee', max_length=10, verbose_name='Результат')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_entries', to='catalog.award', verbose_name='Премия')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_entries', to='catalog.person', verbose_name='Персона')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_entries', to='catalog.title', verbose_name='Произведение')),
            ],
            options={
                'verbose_name': 'Награда произведения',
                'verbose_name_plural': 'Награды произведений',
                'ordering': ['-year', 'award__name', 'category'],
                'indexes': [models.Index(fields=['award', '-year'], name='title_award_award_year_idx'), models.Index(fields=['title', '-year'], name='title_award_title_year_idx')],
                'constraints': [models.UniqueConstraint(fields=('title', 'award', 'person', 'year', 'category'), name='unique_title_award_entry')],
            },
        ),
    ]
