# Generated by Django 5.2.16 on 2026-07-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_award_studio_title_studios_titleaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Просмотров'),
        ),
    ]
