# Generated by Django 5.1.15 on 2026-07-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_award_studio_title_studios_titleaward'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['person', 'role'], name='participation_person_role_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['-published_at'], name='title_published_at_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['status', '-rating_average', '-rating_count'], name='title_status_rating_idx'),
        ),
    ]
