# Generated by Django 5.2.16 on 2026-07-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_view_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['-view_count'], name='title_view_count_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['-rating_average'], name='title_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['status', '-published_at'], name='title_published_idx'),
        ),
    ]
