# Generated by Django 5.2.16 on 2026-08-06 11:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_participation_participation_person_role_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Внешний рейтинг для справки, от 0.0 до 10.0', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг IMDb'),
        ),
        migrations.AddField(
            model_name='title',
            name='kp_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Внешний рейтинг для справки, от 0.0 до 10.0', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг Кинопоиска'),
        ),
        migrations.AddField(
            model_name='title',
            name='quality',
            field=models.CharField(blank=True, choices=[('CAMRip', 'CAMRip'), ('TS', 'TS'), ('TC', 'TC'), ('HDRip', 'HDRip'), ('WEBRip', 'WEBRip'), ('WEB-DL', 'WEB-DL'), ('BDRip', 'BDRip'), ('Blu-ray', 'Blu-ray')], help_text='Например: TC, WEB-DL, BDRip. Показывается в карточке каталога.', max_length=10, verbose_name='Качество'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveSmallIntegerField(default=1, help_text='Для фильма без сезонов оставьте 1', verbose_name='Сезон')),
                ('episode_number', models.PositiveSmallIntegerField(help_text='Номер серии внутри сезона', verbose_name='Серия')),
                ('name', models.CharField(blank=True, help_text='Необязательно, например «Пилот»', max_length=255, verbose_name='Название серии')),
                ('file', models.FileField(help_text='Видео серии (mp4, webm, ogg)', upload_to='episodes/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg'])], verbose_name='Видеофайл')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Длительность, мин')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='catalog.title', verbose_name='Фильм или сериал')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
                'ordering': ['season_number', 'episode_number', 'id'],
                'indexes': [models.Index(fields=['title', 'season_number'], name='episode_title_season_idx')],
                'constraints': [models.UniqueConstraint(fields=('title', 'season_number', 'episode_number'), name='episode_title_season_episode_uniq')],
            },
        ),
    ]
