# Generated by Django 5.2.16 on 2026-08-06 15:08

import apps.catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_title_imdb_rating_title_kp_rating_title_quality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-release_year', 'name', 'pk'], 'verbose_name': 'Фильм или сериал', 'verbose_name_plural': 'Фильмы и сериалы'},
        ),
        migrations.RemoveConstraint(
            model_name='titleaward',
            name='unique_title_award_entry',
        ),
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.FileField(help_text='Видео серии (mp4, webm, ogg)', upload_to='episodes/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg']), apps.catalog.validators.validate_video_signature, apps.catalog.validators.validate_video_size], verbose_name='Видеофайл'),
        ),
        migrations.AlterField(
            model_name='title',
            name='trailer_file',
            field=models.FileField(blank=True, help_text='Своё видео (mp4, webm, ogg). Оставьте пустым, если указываете ссылку.', upload_to='trailers/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg']), apps.catalog.validators.validate_video_signature, apps.catalog.validators.validate_video_size], verbose_name='Видеофайл трейлера'),
        ),
        migrations.AddConstraint(
            model_name='titleaward',
            constraint=models.UniqueConstraint(fields=('title', 'award', 'person', 'year', 'category'), name='unique_title_award_entry', nulls_distinct=False),
        ),
    ]
