# Generated by Django 5.1.15 on 2026-08-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_title_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='latest_episode_info',
            field=models.CharField(blank=True, help_text='Текстовая плашка для сериалов, например: «10 сезон 5 серия».', max_length=120, verbose_name='Последняя серия'),
        ),
        migrations.AddField(
            model_name='title',
            name='player_url_2',
            field=models.URLField(blank=True, help_text='Альтернативный источник просмотра (iframe). Плеер 2 на странице фильма.', verbose_name='Второй плеер'),
        ),
        migrations.AddField(
            model_name='title',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Число просмотров'),
        ),
        migrations.AddField(
            model_name='title',
            name='voice_acting',
            field=models.CharField(blank=True, choices=[('dubbed', 'Дублированный (Лицензия)'), ('lostfilm', 'LostFilm'), ('hdrezka', 'HDRezka Studio'), ('newstudio', 'NewStudio'), ('original', 'Оригинал (Eng.)'), ('subtitles', 'Субтитры'), ('multivoice', 'Многоголосый')], help_text='Как озвучен контент: дубляж, студия или оригинал.', max_length=100, verbose_name='Озвучка / Перевод'),
        ),
        migrations.AlterField(
            model_name='title',
            name='type',
            field=models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал'), ('cartoon', 'Мультфильм'), ('anime', 'Аниме'), ('tv_show', 'ТВ-шоу')], default='movie', max_length=10, verbose_name='Тип'),
        ),
    ]
