# Generated by Django 5.1.15 on 2026-08-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_title_latest_episode_info_title_player_url_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='type',
            field=models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал'), ('cartoon', 'Мультфильм'), ('tv_show', 'ТВ-шоу')], default='movie', max_length=10, verbose_name='Тип'),
        ),
    ]
