# Generated by Django 5.2.16 on 2026-08-10 05:38

import apps.catalog.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_title_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Часть ссылки латиницей, например: dokumentalnyy', max_length=120, unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Озвучка',
                'verbose_name_plural': 'Озвучки',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaybackSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('file', 'Видеофайл'), ('embed', 'Внешний плеер')], default='file', max_length=10, verbose_name='Тип источника')),
                ('file', models.FileField(blank=True, help_text='Для типа «Видеофайл». mp4, webm или ogg.', upload_to='episodes/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg']), apps.catalog.validators.validate_video_signature, apps.catalog.validators.validate_video_size], verbose_name='Видеофайл')),
                ('url', models.URLField(blank=True, help_text='Для типа «Внешний плеер». Хост должен быть из списка доверенных.', verbose_name='Ссылка на плеер')),
                ('quality', models.CharField(blank=True, help_text='Например: WEB-DL, BDRip. Показывается рядом с выбором озвучки.', max_length=10, verbose_name='Качество')),
                ('order', models.PositiveSmallIntegerField(default=100, help_text='Меньше — выше в списке. Первый источник открывается сразу.', verbose_name='Порядок')),
                ('episode', models.ForeignKey(blank=True, help_text='Пусто — источник фильма целиком. Для сериала укажите серию.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playback_sources', to='catalog.episode', verbose_name='Серия')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_sources', to='catalog.title', verbose_name='Фильм или сериал')),
                ('voice', models.ForeignKey(blank=True, help_text='Пусто — единственная озвучка, выбор в плеере не покажем.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='catalog.voiceover', verbose_name='Озвучка')),
            ],
            options={
                'verbose_name': 'Источник видео',
                'verbose_name_plural': 'Источники видео',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['title', 'episode', 'order'], name='playback_title_ep_idx')],
            },
        ),
    ]
