# Generated by Django 5.2.16 on 2026-08-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_backfill_playback_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='file',
        ),
        migrations.RemoveField(
            model_name='title',
            name='player_url_2',
        ),
    ]
