# Generated by Django 5.2.16 on 2026-08-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_drop_legacy_video_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='type',
            field=models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал'), ('cartoon', 'Мультфильм'), ('tv_show', 'ТВ-шоу'), ('anime', 'Аниме')], default='movie', max_length=10, verbose_name='Тип'),
        ),
    ]
