# Generated by Django 5.2.16 on 2026-08-10 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_anime_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Если пусто — возьмётся название', max_length=70, verbose_name='SEO-заголовок')),
                ('meta_description', models.CharField(blank=True, help_text='Если пусто — возьмётся начало описания', max_length=160, verbose_name='SEO-описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Франшиза',
                'verbose_name_plural': 'Франшизы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='title',
            name='franchise',
            field=models.ForeignKey(blank=True, help_text='Серия связанных фильмов: все части, приквелы, спин-оффы.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='catalog.franchise', verbose_name='Франшиза'),
        ),
    ]
