# Generated by Django 5.2.16 on 2026-08-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_drop_anime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='imdb_id',
            field=models.CharField(blank=True, help_text='Например tt0111161. Используется, когда ID Кинопоиска не задан.', max_length=20, verbose_name='ID на IMDb'),
        ),
        migrations.AddField(
            model_name='title',
            name='kp_id',
            field=models.CharField(blank=True, help_text='Например 326. Если заполнен — плеер Vibix покажет фильм по этому ID.', max_length=20, verbose_name='ID на Кинопоиске'),
        ),
    ]
