# Generated by Django 5.2.16 on 2026-08-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_title_imdb_id_title_kp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VibixSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=16, unique=True)),
                ('last_updated_from', models.DateTimeField(blank=True, help_text='Значение параметра updated_from для следующего запуска.', null=True, verbose_name='Синхронизировано по')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Состояние синхронизации Vibix',
                'verbose_name_plural': 'Состояния синхронизации Vibix',
            },
        ),
    ]
