# Generated by Django 5.1.15 on 2026-08-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_vibixsyncstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='vibix_id',
            field=models.CharField(blank=True, help_text='Внутренний ID видео Vibix (data-id из embed_code API).', max_length=20, verbose_name='ID видео Vibix'),
        ),
        migrations.AddField(
            model_name='title',
            name='vibix_type',
            field=models.CharField(blank=True, help_text='Тип эмбеда Vibix: movie или serial (data-type из embed_code API).', max_length=10, verbose_name='Тип видео Vibix'),
        ),
    ]
