# Generated by Django 5.2.16 on 2026-08-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_rename_vibix_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceover',
            name='vibix_voiceover_id',
            field=models.PositiveIntegerField(blank=True, help_text='Заполняется командой sync_voiceovers; id из списка /videos/voiceovers. Передаётся внешнему плееру как data-voiceover.', null=True, verbose_name='ID озвучки в видеосервисе'),
        ),
        migrations.AlterField(
            model_name='title',
            name='player_id',
            field=models.CharField(blank=True, help_text='Внутренний ID видео внешнего плеера (data-id тега плеера).', max_length=20, verbose_name='ID видео в плеере'),
        ),
        migrations.AlterField(
            model_name='title',
            name='player_type',
            field=models.CharField(blank=True, help_text='Тип эмбеда: movie или series (data-type тега плеера).', max_length=10, verbose_name='Тип видео в плеере'),
        ),
    ]
