# Generated by Django 5.2.16 on 2026-08-14 20:22

import apps.catalog.youtube
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_voiceover_vibix_voiceover_id_alter_title_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube-ссылка на полную серию: watch, youtu.be или embed.', validators=[apps.catalog.youtube.validate_youtube_url], verbose_name='Ссылка на полную версию серии'),
        ),
        migrations.AddField(
            model_name='title',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube-ссылка на полный фильм: watch, youtu.be или embed.', validators=[apps.catalog.youtube.validate_youtube_url], verbose_name='Ссылка на полную версию'),
        ),
        migrations.AlterField(
            model_name='title',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube: watch, youtu.be или embed. Оставьте пустым, если загружаете свой видеофайл.', validators=[apps.catalog.youtube.validate_youtube_url], verbose_name='Ссылка на трейлер'),
        ),
    ]
