# Generated by Django 5.2.16 on 2026-07-23 08:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_title_logo_title_related_titles_title_release_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('autoplay_next', models.BooleanField(default=True, verbose_name='Автозапуск следующей серии')),
                ('default_quality', models.CharField(choices=[('auto', 'Авто'), ('2160p', '2160p'), ('1080p', '1080p'), ('720p', '720p'), ('480p', '480p')], default='auto', max_length=8, verbose_name='Качество по умолчанию')),
                ('default_speed', models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2)], verbose_name='Скорость по умолчанию')),
                ('subtitles_language', models.CharField(blank=True, max_length=12, verbose_name='Предпочтительный язык субтитров')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playback_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройка плеера',
                'verbose_name_plural': 'Настройки плеера',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер сезона')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)], verbose_name='Год выпуска')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='catalog.title', verbose_name='Сериал')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер серии')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность, секунд')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('intro_start_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Начало заставки, секунд')),
                ('intro_end_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Конец заставки, секунд')),
                ('recap_start_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Начало рекапа, секунд')),
                ('recap_end_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Конец рекапа, секунд')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='streaming.season', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
                'ordering': ['season__number', 'number'],
            },
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('local', 'Локальное защищённое хранилище'), ('cloudflare_stream', 'Cloudflare Stream'), ('cloudflare_r2', 'Cloudflare R2'), ('aws_s3', 'AWS S3'), ('backblaze_b2', 'Backblaze B2'), ('minio', 'MinIO')], default='local', max_length=32, verbose_name='Провайдер')),
                ('stream_type', models.CharField(choices=[('hls', 'HLS'), ('dash', 'MPEG-DASH'), ('mp4', 'MP4')], default='mp4', max_length=8, verbose_name='Формат доставки')),
                ('asset_key', models.CharField(blank=True, help_text='Непрозрачный ключ файла или манифеста без домена и query-параметров.', max_length=500, validators=[django.core.validators.RegexValidator(message='Ключ файла может содержать только латинские буквы, цифры, точки, подчёркивания, дефисы и слеши.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')], verbose_name='Ключ ресурса у провайдера')),
                ('media_file', models.FileField(blank=True, upload_to='private_media/videos/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'm4v', 'm3u8', 'mpd'])], verbose_name='Локальный видеофайл')),
                ('duration_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность, секунд')),
                ('available_qualities', models.JSONField(blank=True, default=list, help_text='Например: ["auto", "1080p", "720p"]. Для HLS/DASH уровни переключаются адаптером плеера.', verbose_name='Доступные качества')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готов к показу'), ('retired', 'Снят с показа')], default='draft', max_length=10, verbose_name='Статус')),
                ('access_level', models.CharField(choices=[('free', 'Бесплатный'), ('premium', 'Premium'), ('vip', 'VIP'), ('rental', 'Аренда'), ('purchase', 'Покупка')], default='free', max_length=10, verbose_name='Уровень доступа')),
                ('allow_download', models.BooleanField(default=False, verbose_name='Разрешить офлайн-загрузку')),
                ('download_name', models.CharField(blank=True, max_length=255, verbose_name='Имя скачиваемого файла')),
                ('license_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Лицензия действует до')),
                ('episode', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_asset', to='streaming.episode', verbose_name='Серия')),
                ('title', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_asset', to='catalog.title', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Видеоресурс',
                'verbose_name_plural': 'Видеоресурсы',
            },
        ),
        migrations.CreateModel(
            name='SubtitleTrack',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_code', models.CharField(max_length=12, verbose_name='Код языка')),
                ('label', models.CharField(max_length=80, verbose_name='Подпись')),
                ('kind', models.CharField(choices=[('subtitles', 'Субтитры'), ('captions', 'Субтитры для слабослышащих')], default='subtitles', max_length=12, verbose_name='Тип')),
                ('storage_key', models.CharField(blank=True, max_length=500, validators=[django.core.validators.RegexValidator(message='Ключ файла может содержать только латинские буквы, цифры, точки, подчёркивания, дефисы и слеши.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')], verbose_name='Ключ файла')),
                ('subtitle_file', models.FileField(blank=True, upload_to='private_media/subtitles/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['vtt', 'srt'])], verbose_name='Локальный файл субтитров')),
                ('is_default', models.BooleanField(default=False, verbose_name='Включать по умолчанию')),
                ('video_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_tracks', to='streaming.videoasset')),
            ],
            options={
                'verbose_name': 'Дорожка субтитров',
                'verbose_name_plural': 'Дорожки субтитров',
                'ordering': ['language_code', 'label'],
            },
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('position_seconds', models.PositiveIntegerField(default=0, verbose_name='Позиция, секунд')),
                ('duration_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность, секунд')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Просмотр завершён')),
                ('last_watched_at', models.DateTimeField(auto_now=True, verbose_name='Последний просмотр')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to=settings.AUTH_USER_MODEL)),
                ('video_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='streaming.videoasset')),
            ],
            options={
                'verbose_name': 'Прогресс просмотра',
                'verbose_name_plural': 'Прогресс просмотра',
                'ordering': ['-last_watched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['title', 'number'], name='season_title_number_idx'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('title', 'number'), name='unique_season_number'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['season', 'number'], name='episode_season_number_idx'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('season', 'number'), name='unique_episode_number'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['status', 'access_level'], name='asset_status_access_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['provider', 'asset_key'], name='asset_provider_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='videoasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('episode__isnull', True), ('title__isnull', False)), models.Q(('episode__isnull', False), ('title__isnull', True)), _connector='OR'), name='asset_has_exactly_one_content'),
        ),
        migrations.AddConstraint(
            model_name='subtitletrack',
            constraint=models.UniqueConstraint(fields=('video_asset', 'language_code', 'kind'), name='unique_subtitle_track'),
        ),
        migrations.AddIndex(
            model_name='watchprogress',
            index=models.Index(fields=['user', '-last_watched_at'], name='progress_user_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchprogress',
            constraint=models.UniqueConstraint(fields=('user', 'video_asset'), name='unique_asset_watch_progress'),
        ),
    ]
