# Generated by Django 5.2.16 on 2026-07-28 12:11

import apps.streaming.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitletrack',
            name='subtitle_file',
            field=models.FileField(blank=True, storage=apps.streaming.models.private_storage, upload_to='private_media/subtitles/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['vtt', 'srt'])], verbose_name='Локальный файл субтитров'),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='media_file',
            field=models.FileField(blank=True, storage=apps.streaming.models.private_storage, upload_to='private_media/videos/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'm4v', 'm3u8', 'mpd'])], verbose_name='Локальный видеофайл'),
        ),
    ]
