# Generated by Django 5.1.15 on 2026-07-23 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_award_studio_title_studios_titleaward'),
        ('reviews', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='review_user_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['title', 'status', 'rating'], name='review_rating_idx'),
        ),
    ]
