# Generated by Django 5.1.15 on 2026-08-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_review_user_idx_review_review_rating_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='review_user_idx',
        ),
    ]
