# Generated by Django 5.2.16 on 2026-08-10 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_drop_legacy_video_fields'),
        ('reviews', '0004_remove_review_review_user_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('text', models.TextField(max_length=2000, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('published', 'Опубликован'), ('hidden', 'Скрыт')], default='published', max_length=10, verbose_name='Статус')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.comment', verbose_name='Ответ на')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.title', verbose_name='Фильм или сериал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['title', 'status', 'created_at'], name='comment_title_status_idx'), models.Index(fields=['-created_at'], name='comment_created_idx')],
            },
        ),
    ]
